### PR TITLE
Update canvas recording mechanism

### PR DESCRIPTION
**Pull request by yakkomajuri**
Testing out a safer canvas recording mechanism??

Tests pass, example at work:

https://user-images.githubusercontent.com/38760734/109387347-d83c8700-78f8-11eb-8568-0dc7e0055e7c.mov

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Thanks for the demo @yakkomajuri!

I will check this in days, and I'm going to brief the problems I meet when implementing a `safe` canvas replay.

**Comment by timgl** [comment]
@Yuyz0112 Hey, did you get anywhere with this?

**Comment by yakkomajuri** [comment]
@timgl just a quick note that this was a PR on my fork.

The PR upstream got merged: https://github.com/rrweb-io/rrweb/pull/536

**Comment by timgl** [comment]
@yakkomajuri Okay great, so can we turn on canvas recording in posthog-js now?

**Comment by yakkomajuri** [comment]
@timgl Hmm @Yuyz0112 mentioned that my PR ["fixed some issues"](https://github.com/rrweb-io/rrweb/pull/536#issuecomment-859219245) but was unsure that this actually makes canvas recording fully safe:

> The PR looks good to me but I think this will not remove the unsafe flag.

@Yuyz0112 any further thoughts on this?

**Pull request closed without merging**
